### ISSUE TITLE
Services: Recruiting

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#23]
OS X El Capitan 
Version 10.11.3
Firefox 44.0.1

_how it appears online:_
![screen shot 2016-02-11 at 12 58 53 am](https://cloud.githubusercontent.com/assets/7436666/12977459/a5279a66-d07f-11e5-9e45-b714ddc53f0d.png)
Recruiting H3
Content under should be Paragraph

Put a break before "Fees are affordably priced" to create 2 paragraphs.

_how it should be:_
![screen shot 2016-02-11 at 12 59 01 am](https://cloud.githubusercontent.com/assets/7436666/12977460/a52c452a-d07f-11e5-9e77-149fcef20aaf.png)

**Comment by KWenn** [comment]
Confused about the paragraph tags because they are wrapped in <p> tags, additionally, the color of the recruiting square doesn't match my designs that I have. Attaching both an example of the PSD I have and the Style Guide. Both have a blue square, not that grey color. 

![recruitingsample](https://cloud.githubusercontent.com/assets/9420221/13030405/4b1972f2-d25e-11e5-93d2-d01d740fd652.jpg)
<img width="881" alt="screen shot 2016-02-13 at 2 25 20 pm" src="https://cloud.githubusercontent.com/assets/9420221/13030406/5600963c-d25e-11e5-8b59-1a834fa74d43.png">

. I inserted the break to create two paragraphs.

**Comment by Sramos9191** [comment]
@KWenn  not sure why mine appeared with grey but it wasn't an issue I was pointing out, as for the changes made, thank you.
