### ISSUE TITLE
HR News header

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#7]
OS X El Capitan 
Version 10.11.3
Firefox 44.0.1

How it is displayed on the website:
![screen shot 2016-02-11 at 2 45 36 am](https://cloud.githubusercontent.com/assets/7436666/12975564/984731b6-d071-11e5-8946-7010f6da88db.png)
on the Style Guide it is listed as an H6 with the bullet points listed as H7

H6: 
font-size: 3em
line-height: 100%
font: Yanone Kaffeesatz
font-style: regular
color: Frost Blue

H7:
font-size: 1.66em
line-height: 110%
font: lato
font-style: regular
color: black

How it should look:
![screen shot 2016-02-11 at 2 45 42 am](https://cloud.githubusercontent.com/assets/7436666/12975565/984c324c-d071-11e5-879c-176f9a1edb82.png)

**Comment by KWenn** [comment]
Ok, I updated it to match the styles. Since the sidebar is the standard recent posts widget in Wordpress, I cannot add elements to the listed items. I did style the line items according to the above, but as you can see, it is absurdly too big to match the design. I thought I did a pretty good job matching it before so I can revert back. 

updated

**Comment by Sramos9191** [comment]
they are way too big, please revert back - it was closer to matching before.

**Comment by KWenn** [comment]
Updated
